adaptive_bi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: adminpassword
      port: 5432
      dbname: adaptive_bi
      schema: dbt_schema
      threads: 4
      keepalives_idle: 0
